"""initial schema

Revision ID: 9d2393a22114
Revises: 
Create Date: 2026-10-08 13:17:52.749046
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9d2393a22114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('change_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_snapshots',
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('sub_collections', sa.JSON(), nullable=False),
    sa.Column('inaccessible', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('exclusions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exclusions_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mods',
    sa.Column('workshop_id', sa.String(length=24), nullable=False),
    sa.Column('folder_name', sa.String(length=64), nullable=False),
    sa.Column('inventory_state', sa.String(length=16), nullable=False),
    sa.Column('inventory_detail', sa.JSON(), nullable=False),
    sa.Column('cache_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('cache_mtime', sa.BigInteger(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title_local', sa.String(length=512), nullable=False),
    sa.Column('title_remote', sa.String(length=512), nullable=False),
    sa.Column('author_name', sa.String(length=256), nullable=False),
    sa.Column('author_steamid', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('preview_url', sa.String(length=1024), nullable=False),
    sa.Column('remote_file_size', sa.BigInteger(), nullable=True),
    sa.Column('time_published', sa.BigInteger(), nullable=True),
    sa.Column('time_updated', sa.BigInteger(), nullable=True),
    sa.Column('remote_visibility', sa.String(length=32), nullable=False),
    sa.Column('metadata_state', sa.String(length=16), nullable=False),
    sa.Column('metadata_source', sa.String(length=32), nullable=False),
    sa.Column('metadata_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_error', sa.String(length=512), nullable=False),
    sa.Column('desired_state', sa.String(length=16), nullable=False),
    sa.Column('apply_state', sa.String(length=16), nullable=False),
    sa.Column('apply_error', sa.String(length=1024), nullable=False),
    sa.Column('load_source', sa.String(length=32), nullable=False),
    sa.Column('load_sources', sa.JSON(), nullable=False),
    sa.Column('runtime_state', sa.String(length=16), nullable=False),
    sa.Column('requires_restart', sa.Boolean(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('protected_reason', sa.String(length=256), nullable=False),
    sa.Column('deploy_version', sa.Integer(), nullable=False),
    sa.Column('deploy_path', sa.String(length=1024), nullable=False),
    sa.Column('deploy_size', sa.BigInteger(), nullable=False),
    sa.Column('deployed_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_changed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workshop_id')
    )
    with op.batch_alter_table('mods', schema=None) as batch_op:
        batch_op.create_index('ix_mods_apply', ['apply_state'], unique=False)
        batch_op.create_index('ix_mods_desired', ['desired_state'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trash_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=24), nullable=False),
    sa.Column('folder_name', sa.String(length=64), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=False),
    sa.Column('trash_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_desired_state', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_by', sa.String(length=64), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('restore_info', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trash_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trash_entries_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mod_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.String(length=24), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['mods.workshop_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mod_files', schema=None) as batch_op:
        batch_op.create_index('ix_modfiles_wid', ['workshop_id'], unique=False)

    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['change_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.create_index('ix_planitems_plan', ['plan_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.drop_index('ix_planitems_plan')

    op.drop_table('plan_items')
    with op.batch_alter_table('mod_files', schema=None) as batch_op:
        batch_op.drop_index('ix_modfiles_wid')

    op.drop_table('mod_files')
    op.drop_table('users')
    with op.batch_alter_table('trash_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trash_entries_workshop_id'))

    op.drop_table('trash_entries')
    op.drop_table('tasks')
    with op.batch_alter_table('mods', schema=None) as batch_op:
        batch_op.drop_index('ix_mods_desired')
        batch_op.drop_index('ix_mods_apply')

    op.drop_table('mods')
    op.drop_table('kv')
    with op.batch_alter_table('exclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exclusions_workshop_id'))

    op.drop_table('exclusions')
    op.drop_table('collection_snapshots')
    op.drop_table('change_plans')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
